name: Java DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  checkout-code:
    name: Checkout Repository
    runs-on: self-hosted

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Display Working Directory
        run: pwd

      - name: List Repository Files
        run: ls -la
